    [wso2.backoffice_service.datasourceConfiguration]
    description = "Database for admin"
    url = "jdbc:postgresql://10.102.56.192:5432/WSO2AM_DB"
    username = "wso2carbon"
    password = "wso2carbon"
    validationTimeout = 250
    testQuery = "SELECT 1"
    driver = "org.postgresql.Driver"
    host = "10.102.56.192"
    port = 5432
    databaseName = "WSO2AM_DB"
    [wso2.backoffice_service.k8sConfig]
    host = "localhost:9090"
    serviceAccountPath = "tests/resources/serviceAccount"

    [wso2.backoffice_service.managementServerConfig]
    serviceName = "apk-test-wso2-apk-management-server"
    namespace = "apk"
    certPath = "/home/wso2apk/backoffice/security/truststore/management-server.pem"
